# Generated by Django 5.1.5 on 2025-01-27 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_supplier', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('gstn', models.CharField(max_length=15)),
                ('pan', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('name_of_buyer', models.CharField(max_length=255)),
                ('buyer_state', models.CharField(max_length=255)),
                ('buyer_gstn', models.CharField(max_length=15)),
                ('buyer_pan', models.CharField(max_length=10)),
                ('buyer_address', models.TextField()),
                ('invoice_date', models.DateField()),
                ('delivery_note_no', models.CharField(max_length=255)),
                ('buyer_order_no', models.CharField(max_length=255)),
                ('despatch_document_no', models.CharField(max_length=255)),
                ('despatch_mode', models.CharField(max_length=255)),
                ('date_of_despatch', models.DateField()),
                ('vehicle_no', models.CharField(max_length=255)),
                ('shipping_address', models.TextField()),
                ('item_name', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(max_length=255)),
                ('gst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('uom', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(max_length=255)),
                ('gst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('uom', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='bill_genearator.invoice')),
            ],
        ),
    ]
