# Generated by Django 5.1.5 on 2025-01-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_genearator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
