# Generated by Django 5.2 on 2025-04-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_genearator', '0003_invoiceitem_cgst_invoiceitem_sgst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
