# Generated by Django 5.2 on 2025-04-18 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_genearator', '0006_alter_invoice_buyer_gstn_alter_invoice_buyer_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='gstn',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pan',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
