# Generated by Django 5.2 on 2025-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_genearator', '0007_alter_invoice_gstn_alter_invoice_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(default='TEMP-INV', max_length=100, unique=True),
        ),
    ]
