# Generated by Django 5.2 on 2025-04-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_genearator', '0008_invoice_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(default='TEMP-INV', max_length=100),
        ),
    ]
