# Generated by Django 5.2 on 2025-05-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_genearator', '0010_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='terms_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
